baseURL = 'https://status.winti.social/'
languageCode = 'de-CH'
title = 'Status Seite für winti.social'
theme = "yinyang"

[params]
mainSections = ["posts"]
headTitle = "winti.social Status"

[[params.socials]]
name = "winti.social Mastodon"
link = "https://winti.social"
[[params.socials]]
name = "Über winti.social"
link = "https://about.winti.social"
[[params.socials]]
name = "winti.social Statusseite"
link = "https://status.winti.social"
